# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'CoB2n appXyByjm.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide6.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(954, 548)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowTitle(u"CoB2n")
        MainWindow.setStyleSheet(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, -1, 951, 501))
        self.tabWidget.setStyleSheet(u"")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.chartTab2 = QGroupBox(self.tab)
        self.chartTab2.setObjectName(u"chartTab2")
        self.chartTab2.setGeometry(QRect(0, 50, 731, 421))
        self.charTab1 = QGroupBox(self.tab)
        self.charTab1.setObjectName(u"charTab1")
        self.charTab1.setGeometry(QRect(0, 10, 731, 41))
        self.label_2 = QLabel(self.charTab1)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 14, 21, 16))
        self.lineEdit = QLineEdit(self.charTab1)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(40, 9, 531, 21))
        self.pushButton_3 = QPushButton(self.charTab1)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(690, 10, 31, 21))
        self.comboBox_3 = QComboBox(self.charTab1)
        self.comboBox_3.addItem("")
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(580, 10, 101, 22))
        self.chartTab3 = QGroupBox(self.tab)
        self.chartTab3.setObjectName(u"chartTab3")
        self.chartTab3.setGeometry(QRect(740, 10, 201, 461))
        self.comboBox_2 = QComboBox(self.chartTab3)
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(10, 10, 181, 22))
        self.groupBox = QGroupBox(self.chartTab3)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 40, 181, 241))
        self.checkBox = QCheckBox(self.chartTab3)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(20, 300, 51, 16))
        self.checkBox_2 = QCheckBox(self.chartTab3)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(80, 300, 51, 16))
        self.checkBox_3 = QCheckBox(self.chartTab3)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setGeometry(QRect(140, 300, 51, 16))
        self.checkBox_4 = QCheckBox(self.chartTab3)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.checkBox_4.setGeometry(QRect(20, 320, 51, 16))
        self.checkBox_5 = QCheckBox(self.chartTab3)
        self.checkBox_5.setObjectName(u"checkBox_5")
        self.checkBox_5.setGeometry(QRect(80, 320, 51, 16))
        self.label_3 = QLabel(self.chartTab3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 350, 56, 12))
        self.lineEdit_2 = QLineEdit(self.chartTab3)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(20, 370, 171, 20))
        self.pushButton_4 = QPushButton(self.chartTab3)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(20, 410, 75, 23))
        self.pushButton_5 = QPushButton(self.chartTab3)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(110, 410, 75, 23))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.strategy_combo = QComboBox(self.tab_2)
        self.strategy_combo.addItem("")
        self.strategy_combo.addItem("")
        self.strategy_combo.addItem("")
        self.strategy_combo.addItem("")
        self.strategy_combo.setObjectName(u"strategy_combo")
        self.strategy_combo.setGeometry(QRect(10, 10, 211, 22))
        self.strategy_setting = QFrame(self.tab_2)
        self.strategy_setting.setObjectName(u"strategy_setting")
        self.strategy_setting.setGeometry(QRect(10, 40, 451, 431))
        self.strategy_setting.setFrameShape(QFrame.StyledPanel)
        self.strategy_setting.setFrameShadow(QFrame.Raised)
        self.strategy_block = QFrame(self.tab_2)
        self.strategy_block.setObjectName(u"strategy_block")
        self.strategy_block.setGeometry(QRect(470, 40, 471, 211))
        self.strategy_block.setFrameShape(QFrame.StyledPanel)
        self.strategy_block.setFrameShadow(QFrame.Raised)
        self.scrollArea = QScrollArea(self.strategy_block)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(0, 0, 471, 211))
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 469, 209))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.history = QFrame(self.tab_2)
        self.history.setObjectName(u"history")
        self.history.setGeometry(QRect(470, 260, 471, 211))
        self.history.setFrameShape(QFrame.StyledPanel)
        self.history.setFrameShadow(QFrame.Raised)
        self.listView = QListView(self.history)
        self.listView.setObjectName(u"listView")
        self.listView.setGeometry(QRect(0, 0, 471, 211))
        self.tabWidget.addTab(self.tab_2, "")
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(0, 500, 951, 31))
        self.pushButton = QPushButton(self.widget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(870, 0, 75, 23))
        self.pushButton_2 = QPushButton(self.widget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(790, 0, 75, 23))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        self.chartTab2.setTitle("")
        self.charTab1.setTitle("")
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"API", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"\uc800\uc7a5", None))
        self.comboBox_3.setItemText(0, QCoreApplication.translate("MainWindow", u"Upbit", None))

        self.chartTab3.setTitle("")
        self.comboBox_2.setItemText(0, QCoreApplication.translate("MainWindow", u"\uc120\ud0dd", None))

        self.groupBox.setTitle("")
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"10%", None))
        self.checkBox_2.setText(QCoreApplication.translate("MainWindow", u"25%", None))
        self.checkBox_3.setText(QCoreApplication.translate("MainWindow", u"50%", None))
        self.checkBox_4.setText(QCoreApplication.translate("MainWindow", u"75%", None))
        self.checkBox_5.setText(QCoreApplication.translate("MainWindow", u"\ucd5c\ub300", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\uc9c1\uc811\uc785\ub825", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"PushButton", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"PushButton", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"\ucc28\ud2b8", None))
        self.strategy_combo.setItemText(0, QCoreApplication.translate("MainWindow", u"\uae30\ubcf8\uc804\ub7b5", None))
        self.strategy_combo.setItemText(1, QCoreApplication.translate("MainWindow", u"Custom 1", None))
        self.strategy_combo.setItemText(2, QCoreApplication.translate("MainWindow", u"Custom 2", None))
        self.strategy_combo.setItemText(3, QCoreApplication.translate("MainWindow", u"Custom 3", None))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"\uc2e4\ud589", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\uc2e4\ud589", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"\uc911\uc9c0", None))
    # retranslateUi

