# Generated by Django 5.1.5 on 2025-02-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobin_app', '0003_infopost_post_author_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
