# Generated by Django 5.1.5 on 2025-03-10 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobin_app', '0010_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
