# Generated by Django 5.1.7 on 2025-03-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobin_app', '0011_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='point1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='point2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
