# Generated by Django 5.1.7 on 2025-03-31 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobin_app', '0012_userprofile_point1_userprofile_point2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='point2',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(960)]),
        ),
    ]
