# Generated by Django 5.1.7 on 2025-04-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobin_app', '0013_alter_userprofile_point2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('in_progress', '진행 중'), ('completed', '완료')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('free', '자유'), ('info', '정보'), ('proposal', '제안'), ('strategy', '전략'), ('event', '이벤트'), ('notice', '공지사항'), ('qna', 'Q&A'), ('etc', '기타'), ('bug', '버그제보')], default='free', max_length=20),
        ),
    ]
