# Generated by Django 5.1.7 on 2025-04-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobin_app', '0014_post_status_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('in_progress', '진행 중'), ('completed', '완료')], default='completed', max_length=20),
        ),
    ]
